<a href="https://colab.research.google.com/github/simran2352/suhana-/blob/main/pandass.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
ds1=pd.Series([2,4,8,10])
ds2=pd.Series([1,3,7,9])
print("multiply two series:")
ds=ds1*ds2
print(ds)
print("divide series1 by series2:")
ds=ds1/ds2
print(ds)

multiply two series:
0     2
1    12
2    56
3    90
dtype: int64
divide series1 by series2:
0    2.000000
1    1.333333
2    1.142857
3    1.111111
dtype: float64


In [ ]:
import pandas as pd
d1={'a':100,'b':200,'c':300}
print("original dictionary")
print(d1)
new_Series=pd.Series(d1)
print("converted series:")
print(new_Series)

original dictionary
{'a': 100, 'b': 200, 'c': 300}
converted series:
a    100
b    200
c    300
dtype: int64


In [ ]:
import pandas as pd
S=pd.Series([400,300.12,100,200])
print("original data series:")
print(S)
new_S=pd.Series(S).sort_values()
print(new_S)

original data series:
0    400.00
1    300.12
2    100.00
3    200.00
dtype: float64
2    100.00
3    200.00
1    300.12
0    400.00
dtype: float64


In [ ]:
import pandas as pd
S=pd.Series(data=[1,2,3],index=['A','B','C'])
print("original data Series:")
print(S)
S=S.reindex(index=['B','A','C'])
print("data Series after changing the order of index:")
print(S)

original data Series:
A    1
B    2
C    3
dtype: int64
data Series after changing the order of index:
B    2
A    1
C    3
dtype: int64


In [ ]:
import pandas as pd
import numpy as np
sr1=pd.Series([1,2,3])
sr2=pd.Series([2,3,6])
print("original Series:")
print("sr1:")
print(sr1)
print("sr2:")
print(sr2)
print("\n items of a given Series not present in another given Series:")
sr11=pd.Series(np.union1d(sr1,sr2))
sr22=pd.Series(np.intersect1d(sr1,sr2))
result=sr11[~sr11.isin(sr22)]
print(result)

original Series:
sr1:
0    1
1    2
2    3
dtype: int64
sr2:
0    2
1    3
2    6
dtype: int64

 items of a given Series not present in another given Series:
0    1
3    6
dtype: int64


In [ ]:
import pandas as pd
import numpy as np
exam_data={'name':['manish','dhiraj'],'score':[12.5,9]}
labels=['NAME','SCORE']
df=pd.DataFrame(exam_data,index=labels)
print(df)

         name  score
NAME   manish   12.5
SCORE  dhiraj    9.0


In [ ]:
import pandas as pd
import numpy as np
exam_data={'name':['manish','dhiraj','man','dhir'],'score':[12.5,91,2.5,9]}
df=pd.DataFrame(exam_data)
print("first three rows of dataframe")
print(df.iloc[:3])

first three rows of dataframe
     name  score
0  manish   12.5
1  dhiraj   91.0
2     man    2.5


In [ ]:
import pandas as pd
import numpy as np
exam_data={'name':['manish','dhiraj','man','dhir'],'score':[12.5,91,2.5,9]}
df=pd.DataFrame(exam_data)
total_rows=len(df.axes[0])
total_cols=len(df.axes[1])
print("number of rows:"+str(total_rows))
print("total numbers of cols:"+str(total_cols))

number of rows:4
total numbers of cols:2


In [ ]:
import pandas as pd
import numpy as np
exam_data={'name':['manish','dhiraj','man','dhir'],'score':[12.5,91,20.5,19]}
df=pd.DataFrame(exam_data)
print("rows where score between 15and20")
print(df[df['score'].between(15,20)])

rows where score between 15and20
   name  score
3  dhir   19.0


In [ ]:
import pandas as pd
import numpy as np
exam_data = {'name': ['Manish', 'Dhiraj','Man', 'Dhir'],
 'score': [12.5, 91,20.5, 19]}
df = pd.DataFrame(exam_data )
result_sort=df.sort_values(by=['name','score'], ascending=[True,
True])
print("Sort the DataFrame first by 'name' in descending order, then by'score' in ascending order:")
print(result_sort)

Sort the DataFrame first by 'name' in descending order, then by'score' in ascending order:
     name  score
3    Dhir   19.0
1  Dhiraj   91.0
2     Man   20.5
0  Manish   12.5


In [ ]:
import pandas as pd
import numpy as np
exam_data = {'name': ['Manish', 'Dhiraj','Man', 'Dhir'],
 'score': [12.5, 91,20.5, 19]}
df = pd.DataFrame(exam_data )
df['name'] = df['name'].replace('Manish', 'Anish')
print(df)

     name  score
0   Anish   12.5
1  Dhiraj   91.0
2     Man   20.5
3    Dhir   19.0


In [ ]:
import pandas as pd
import numpy as np
exam_data = {'name': ['Manish', 'Dhiraj','Man', 'Dhir'],
 'score': [12.5, 91,20.5, 19]}
df = pd.DataFrame(exam_data )
medium = ['english','hindi','hindi','english']
df['medium'] = medium
print("\nNew DataFrame after inserting the 'medium' column")
print(df)


New DataFrame after inserting the 'medium' column
     name  score   medium
0  Manish   12.5  english
1  Dhiraj   91.0    hindi
2     Man   20.5    hindi
3    Dhir   19.0  english


In [ ]:
import numpy as np
exam_data = {'name': ['Manish', 'Dhiraj','Man', 'Dhir'],
 'score': [12.5, 91,20.5, 19]}
df = pd.DataFrame(exam_data )
df = df.rename(columns={'name': 'NAME', 'score': 'SCORE'})
print("New DataFrame after renaming columns:")
print(df)

New DataFrame after renaming columns:
     NAME  SCORE
0  Manish   12.5
1  Dhiraj   91.0
2     Man   20.5
3    Dhir   19.0


In [ ]:
import pandas as pd
import numpy as np
exam_data = {'name': ['Manish', 'Dhiraj','Man', 'Dhir'],
 'score': [12.5, 91,20.5, 19]}
df = pd.DataFrame(exam_data )
df = df[df.score >= 20]
print("New DataFrame")
print(df)

New DataFrame
     name  score
1  Dhiraj   91.0
2     Man   20.5


In [ ]:
import pandas as pd
import numpy as np
s1 = pd.Series(['100', '200', '400'])
s2 = pd.Series(['10', '20', '40'])
print("Data Series:")
print(s1)
print(s2)
df = pd.concat([s1, s2], axis=1)
print("New DataFrame combining two series:")
print(df)

Data Series:
0    100
1    200
2    400
dtype: object
0    10
1    20
2    40
dtype: object
New DataFrame combining two series:
     0   1
0  100  10
1  200  20
2  400  40


In [ ]:
import pandas as pd
import numpy as np
s1 = pd.Series(['100', '200', '400'])
s2 = pd.Series(['10', '20', '40'])
df = pd.concat([s1, s2], axis=1)
print("Value of Row4")
print(df.iloc[2])

Value of Row4
0    400
1     40
Name: 2, dtype: object


In [ ]:
import pandas as pd
import numpy as np
s1 = pd.Series(['100', '200', '400'])
s2 = pd.Series(['10', '20', '40'])
df = pd.concat([s1, s2], axis=1)
new_col = [1, 2, 3]

idx = 0
df.insert(loc=idx, column='1', value=new_col)
print("\nNew DataFrame")
print(df)


New DataFrame
   1    0   1
0  1  100  10
1  2  200  20
2  3  400  40


In [ ]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr.mean())
print(arr.min())
print(arr.max())
print(arr.std())

2.5
1
4
1.118033988749895


In [ ]:
import numpy as np
import random
array=np.random.randint(16,size=(4,4))
print("input array =in",array)
print("largest numner in x axis,",np.max(array,axis=1))
print("largest number in y axis,",np.max(array,axis=0))

input array =in [[ 9  7  6  9]
 [11 10 13 14]
 [11  2  9  9]
 [ 4  5  6  5]]
largest numner in x axis, [ 9 14 11  6]
largest number in y axis, [11 10 13 14]


In [ ]:
import numpy as np
import random
array = np.random.randint(16,size=(4,4))
print("Input Array: \n",array)
print("Smallest number in x axis: ",np.min(array,axis=1))
print("Smallest number in y axis: ",np.min(array,axis=0))

Input Array: 
 [[10  6  5  9]
 [ 0 11  4 13]
 [11 13  6  9]
 [11 12  9  8]]
Smallest number in x axis:  [5 0 6 8]
Smallest number in y axis:  [0 6 4 8]


In [ ]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr+2)

[3 4 5 6]


In [ ]:
import numpy as np
arr=np.array([1,2,3,4])
print(np.sin(arr))

[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]


In [ ]:
arr = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])
print(arr + arr2)

[2 4 6]


In [ ]:
squared = list(map(lambda x: x**2, arr))
print("Squared using map:", squared)

Squared using map: [np.int64(1), np.int64(4), np.int64(9)]


In [ ]:
def square(number):
    return number*number
nums= [1,2,3,4]
squared_numbers = list(map(square,nums))
print(squared_numbers)

[1, 4, 9, 16]


In [ ]:
nums1= [1,2,3,4,5,6]
squareOfnums1 = list(map(lambda n:n*n,nums1))
print(squareOfnums1)

[1, 4, 9, 16, 25, 36]


In [ ]:
def is_even(n):
if n % 2 ==0:
return True
else:
return False
nums = [1,2,3,4]
evens = list(filter(is_even,nums))
print(evens)

In [ ]:
ven = list(filter(lambda x: x % 2 == 0, arr))
print("Even numbers:", even)

In [ ]:
def sum_all(a,b):
return a+b
nums = [1,2,3,4]
sum = reduce(sum_all,nums)
print(sum)

In [ ]:
total = reduce(lambda x, y: x + y, arr)
print("Sum using reduce:", total)

In [ ]:
nums = [1,2,3,4]
evens = list(filter(lambda n:n%2==0,nums))
print(evens)

In [ ]:
data = pd.Series([10, 20, 30, 40], index=['a', 'b', 'c', 'd'])
print(data)

In [ ]:
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35],
    'City': ['Delhi', 'Mumbai', 'Bangalore']
}
df = pd.DataFrame(data)
print(df)

In [ ]:
import pandas as pd
# Reading from CSV
df = pd.read_csv('/content/students.csv')
# Writing to CSV
df.to_csv('output.csv', index=False)
print(df)

       names  S1  S2
0      mahek  97  89
1      laxmi  95  91
2  vaishnavi  93  90


In [ ]:
import pandas as pd
lst = ['Apple', 'Mango', 'Banana', 'Pine Apple', 'Grapes', 'Watermelon']

df = pd.DataFrame(lst)
print(df)

            0
0       Apple
1       Mango
2      Banana
3  Pine Apple
4      Grapes
5  Watermelon


In [ ]:
import pandas as pd
data ={'Name':['Tom', 'nick', 'krish', 'jack'], 'Age':[20, 21, 19, 18]}
df = pd.DataFrame(data)
print(df)

    Name  Age
0    Tom   20
1   nick   21
2  krish   19
3   jack   18


In [ ]:
import pandas as pd
data = {
    'Department': ['HR', 'HR', 'IT', 'IT', 'Finance', 'Finance'],
    'Employee': ['Alice', 'Bob', 'Charlie', 'David', 'Eva', 'Frank'],
    'Salary': [50000, 55000, 60000, 65000, 70000, 72000],
     'Age': [25, 30, 28, 32, 40, 38]
}
df = pd.DataFrame(data)
print(df)

  Department Employee  Salary  Age
0         HR    Alice   50000   25
1         HR      Bob   55000   30
2         IT  Charlie   60000   28
3         IT    David   65000   32
4    Finance      Eva   70000   40
5    Finance    Frank   72000   38


In [ ]:
import pandas as pd
d1 = {"Name": ["Pankaj", "Lisa", "David"], "ID": [1, 2, 3], "Role": ["CEO", "Editor", "Author"]}
df = pd.DataFrame(d1)
print(df)
df_melted = pd.melt(df, id_vars=["ID"],
value_vars=["Name", "Role"])
print(df_melted)


     Name  ID    Role
0  Pankaj   1     CEO
1    Lisa   2  Editor
2   David   3  Author
   ID variable   value
0   1     Name  Pankaj
1   2     Name    Lisa
2   3     Name   David
3   1     Role     CEO
4   2     Role  Editor
5   3     Role  Author


In [ ]:
import pandas as pd
data = {
    'Date': ['2024-01-01', '2024-01-01', '2024-01-02', '2024-01-02'],
    'City': ['Mumbai', 'Delhi', 'Mumbai', 'Delhi'],
    'Temperature': [33, 28, 34, 27]
}
df = pd.DataFrame(data)
print("Original:\n", df)
pivoted = df.pivot(index='Date', columns='City', values='Temperature')
print("\nPivoted:\n", pivoted)

Original:
          Date    City  Temperature
0  2024-01-01  Mumbai           33
1  2024-01-01   Delhi           28
2  2024-01-02  Mumbai           34
3  2024-01-02   Delhi           27

Pivoted:
 City        Delhi  Mumbai
Date                     
2024-01-01     28      33
2024-01-02     27      34


In [ ]:
import pandas as pd
# Create a sample DataFrame
data = {
    'Student': ['Alice', 'Bob', 'Charlie'],
    'Math': [85, 90, 78],
    'Science': [92, 88, 85],
    'English': [75, 80, 72]
}
df = pd.DataFrame(data)
print("Original Wide DataFrame:\n", df)


Original Wide DataFrame:
    Student  Math  Science  English
0    Alice    85       92       75
1      Bob    90       88       80
2  Charlie    78       85       72
